name: Go
on: [push]
jobs:

  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.go }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        go: ['1.10' , '1.11' , '1.12']
        os: [ubuntu, windows, macOS]
    steps:
     
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...
       
    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -p 1 -race -v ./... -coverprofile=coverage.txt --coverpkg="$(go list ./... | tr '\n' ',')"
    
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
        flags: go${{ matrix.go }}-${{ matrix.os }}
