name: Go
on: [push]
jobs:

  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.go }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        go: ['1.10' , '1.11' , '1.12']
        os: [ubuntu, windows, macOS]
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        COVERAGE_TAG: go${{ matrix.golang_version}}-${{ matrix.os}}
    steps:
    - name: Set up Go ${{ matrix.golang_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...
       
    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -p 1 -race -v ./... -coverprofile=coverage.txt --coverpkg="$(go list ./... | tr '\n' ',')"
    
    - name: Upload coverage
      run: bash <(curl -s https://codecov.io/bash) -cF 
