name: Go
on: [push]
jobs:

  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.10' , '1.11' , '1.12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Set up Go ${{ matrix.golang_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...
       
    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -p 1 -race -v ./...
